{
 "title": "Analytics Core - Pending Tasks Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending Tasks By Server",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core01.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core01"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core02.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core02"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core03.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core03"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core04.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core04"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core05.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core05"
    }
   ]
  },
  {
   "title": "Pending Tasks By Task Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"AddElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "AddElasticube"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"DeleteElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "DeleteElasticube"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"PopulateDatabase\"})",
     "legendFormat": "PopulateDatabase"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"ReplaceElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "ReplaceElasticube"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"RebuildElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "RebuildElasticube"
    }
   ]
  },
  {
   "title": "Pending Tasks By Organization Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{organization_type=~\"Parent\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Parent"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{organization_type=~\"Child\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Child"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{organization_type=~\"Unknown\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Pending Tasks By Product",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{product_type=~\"Surveillance\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Surveillance"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{product_type=~\"Poca\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "POCA"
    }
   ]
  },
  {
   "title": "Pending Tasks By Server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core01.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core01"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core02.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core02"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core03.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core03"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core04.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core04"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{instance=~\"prod-rep-core05.hpl.com:9007\"})",
     "legendFormat": "prod-rep-core05"
    }
   ]
  },
  {
   "title": "Pending Tasks By Task Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"DeleteElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "DeleteElasticube"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"AddElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "AddElasticube"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"PopulateDatabase\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "PopulateDatabase"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"ReplaceElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "ReplaceElasticube"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"RebuildElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "RebuildElasticube"
    }
   ]
  },
  {
   "title": "Pending Tasks By Organization Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{organization_type=~\"Unknown\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{organization_type=~\"Parent\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Parent"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{organization_type=~\"Child\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Child"
    }
   ]
  },
  {
   "title": "Pending Tasks By Product",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{product_type=~\"Poca\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "POCA"
    },
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{product_type=~\"Surveillance\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "Surveillance"
    }
   ]
  },
  {
   "title": "Pending AddElasticube Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(p1s_analyticscore_worklist_tasks_filtered{task_type=~\"AddElasticube\", instance=~\"prod-rep-core.*\"})",
     "legendFormat": "AddElasticube"
    }
   ]
  }
 ]
}