{
 "title": "Asus RT-AX58U",
 "description": "Monitoring for Asus RT-AX88U",
 "tags": [ "asus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "dbInflux", "label": "dbInflux", "query": "influxdb" },
   {
    "name": "routerHost",
    "label": "router",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" "
   },
   {
    "name": "trafficHosts",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\" "
   },
   {
    "name": "routerHostsWifi",
    "label": "Wifi Hosts",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\" WHERE \"router.wifi.clients2\" =~ //"
   },
   {
    "name": "Interfaces",
    "label": "Interfaces",
    "query": "SHOW TAG VALUES WITH KEY = \"interface\" "
   },
   {
    "name": "filesystem",
    "label": "Filesystem",
    "query": "SHOW TAG VALUES WITH KEY = \"MountedOn\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "user" ], "type": "tag" },
        { "params": [ "appname" ], "type": "tag" }
       ],
       "measurement": "syslog",
       "select": [
        [
         { "params": [ "procid" ], "type": "field" }
        ],
        [
         { "params": [ "facility_code" ], "type": "field" }
        ],
        [
         { "params": [ "severity_code" ], "type": "field" }
        ],
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHost$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "type": "larona-epict-panel",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 11, "x": 5, "y": 2 },
   "options": {
    "content": "<span class=\"singlestat-panel-value\" style=\"font-size:60.400000000000002px\">Lucasnet RT-AX58U on AsusWRT-Merlin </span>"
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.versions",
     "query": "SELECT mean(\"value\") FROM \"router.versions\" WHERE (\"host\" =~ /^$routerHost$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.versions",
     "select": [
      [
       { "params": [ "buildno" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "larona-epict-panel",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load Average",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "router.cpu",
     "query": "SELECT (100 - mean(\"idle\")) as cpu FROM \"router.cpu\" WHERE (\"host\" =~ /^$routerHost$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "usr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "JFFS Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "router.filesystem",
     "select": [
      [
       { "params": [ "FreePercent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "Filesystem", "operator": "=", "value": "/dev/mtdblock9" }
     ]
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.mem",
     "select": [
      [
       { "params": [ "free_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Free swap Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.swap",
     "select": [
      [
       { "params": [ "swap_free_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHostsWifi$/" }
     ]
    }
   ]
  },
  {
   "title": "Available Swap",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.swap",
     "select": [
      [
       { "params": [ "swap_free_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.uptime",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Clients",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "2.4 ghz",
     "measurement": "router.connections",
     "select": [
      [
       { "params": [ "wifi_24" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    },
    {
     "alias": "5 ghz",
     "measurement": "router.connections",
     "select": [
      [
       { "params": [ "wifi_5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Open VPN AWS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.vpnClients",
     "select": [
      [
       { "params": [ "tcp_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "vpn_client", "operator": "=", "value": "vpn_client1" }
     ]
    }
   ]
  },
  {
   "title": "Open VPN Azure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.vpnClients",
     "select": [
      [
       { "params": [ "tcp_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "vpn_client", "operator": "=", "value": "vpn_client2" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "2.4 ghz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.temp",
     "select": [
      [
       { "params": [ "temp_24" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    },
    {
     "alias": "5 ghz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.temp",
     "select": [
      [
       { "params": [ "temp_50" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  { "title": "Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU $col time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "usr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "user" ], "type": "alias" }
      ],
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "system" ], "type": "alias" }
      ],
      [
       { "params": [ "irq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "irq" ], "type": "alias" }
      ],
      [
       { "params": [ "io" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "io" ], "type": "alias" }
      ],
      [
       { "params": [ "nic" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "nice" ], "type": "alias" }
      ],
      [
       { "params": [ "sirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "softirq" ], "type": "alias" }
      ],
      [
       { "params": [ "idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "idle" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Processor load (1 min average per core)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Processor load (5 min average per core)"
        ],
        "type": "alias"
       }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         "Processor load (15 min average per core)"
        ],
        "type": "alias"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.cpu",
     "select": [
      [
       { "params": [ "processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Number of Processes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.mem",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "free_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "free" ], "type": "alias" }
      ],
      [
       { "params": [ "used_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  { "title": "Wifi / WAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "🛰️⬇️  WAN in",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth4" }
     ]
    }
   ]
  },
  {
   "title": "🛰️⬆️ WAN out",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth4" }
     ]
    }
   ]
  },
  {
   "title": "🛰️⬇️  WAN in",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth3" }
     ]
    }
   ]
  },
  {
   "title": "🛰️⬆️ WAN out",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth3" }
     ]
    }
   ]
  },
  {
   "title": "🛰️ Traffic Router to WAN0 - eth4",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth4" }
     ]
    }
   ]
  },
  {
   "title": "🛰️ Traffic Router to WAN1 - eth3",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ],
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth3" }
     ]
    }
   ]
  },
  {
   "title": "WiFi",
   "type": "larona-epict-panel",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "📶⬆️ WiFi 5ghz upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth6" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth6" }
     ]
    }
   ]
  },
  {
   "title": "📶⬇️ WiFi 5ghz down",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth6" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth6" }
     ]
    }
   ]
  },
  {
   "title": "📶⬆️ WiFi 2.4ghz upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth5" }
     ]
    }
   ]
  },
  {
   "title": "📶⬇️ WiFi 2.4ghz down",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "eth5" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "eth5" }
     ]
    }
   ]
  },
  {
   "title": "WiFi",
   "type": "larona-epict-panel",
   "gridPos": { "h": 15, "w": 4, "x": 20, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connected WiFi Clients",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 4, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.connections",
     "select": [
      [
       { "params": [ "wifi_24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "2,4ghz Clients" ], "type": "alias" }
      ],
      [
       { "params": [ "wifi_5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5ghz Clients" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem $filesystem",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 55 },
     "repeat": "filesystem",
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.filesystem",
       "select": [
        [
         { "params": [ "Available" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "free" ], "type": "alias" }
        ],
        [
         { "params": [ "Used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Used" ], "type": "alias" }
        ],
        [
         { "params": [ "blocks" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Total" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
        { "condition": "AND", "key": "MountedOn", "operator": "=~", "value": "/^$filesystem$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "VPN / TUN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "OpenVPN Client3 ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.vpnClients",
     "select": [
      [
       { "params": [ "auth_r" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "Auth read" ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_r" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TCP/UDP read " ], "type": "alias" }
      ],
      [
       { "params": [ "tcp_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TCP/UDP write" ], "type": "alias" }
      ],
      [
       { "params": [ "tun_r" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TUN/TAP read " ], "type": "alias" }
      ],
      [
       { "params": [ "tun_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "TUN/TAP write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "🛰️ VPN Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "tun21" }
     ]
    }
   ]
  },
  { "title": "Wifi rsi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Wifi rssi",
   "type": "gauge",
   "description": "-30 dBm \tAmazing \t\n-67 dBm \tVery Good \t\n-70 dBm \tOkay \t\n-80 dBm \tNot Good \t\n-90 dBm \tUnusable \t",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients2",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Clients rssi",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname ($tag_client) [$tag_ip]",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "client" ], "type": "tag" },
      { "params": [ "ip" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients2",
     "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise Antenna",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "dBm" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.wifi.clients",
     "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
     "select": [
      [
       { "params": [ "noise_antenna_1" ], "type": "field" },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$routerHost$/" }
     ]
    }
   ]
  },
  {
   "title": "Connstats / Speedtest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ping & Jitter",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Ping",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.uptime",
       "select": [
        [
         { "params": [ "Ping" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Jitter",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.uptime",
       "select": [
        [
         { "params": [ "Jitter" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Packet Loss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "Packet_Loss",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.uptime",
       "select": [
        [
         { "params": [ "Packet_Loss" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Speedtest Download",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "alias": "Download",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.spdstats",
       "select": [
        [
         { "params": [ "Download" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Speedtest Upload",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "MBs" }
     ],
     "targets": [
      {
       "alias": "Upload",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.spdstats",
       "select": [
        [
         { "params": [ "Upload" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic by Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic by Client - out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_hostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "router.client_traffic",
       "select": [
        [
         { "params": [ "outBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "tx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
       ]
      }
     ]
    },
    {
     "title": "Traffic by Client - in",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 85 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_hostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.client_traffic",
       "select": [
        [
         { "params": [ "inBytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "rx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
        { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
       ]
      }
     ]
    },
    {
     "title": "Client actual Traffic Download",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$col $tag_hostname",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "router.trafficAnalyzer",
       "select": [
        [
         { "params": [ "rx" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "rx" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "$routerHostsWifi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "repeat": "routerHostsWifi",
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "wifiBand" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "select": [
        [
         { "params": [ "wifiBand" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "select": [
        [
         { "params": [ "online" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "select": [
        [
         { "params": [ "online" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "client" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "select": [
        [
         { "params": [ "online" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "select": [
        [
         { "params": [ "online" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "select": [
        [
         { "params": [ "online" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "title": "RSSI",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 120 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "query": "SELECT moving_average(\"rsi_antenna1\", 5), moving_average(\"rsi_antenna2\", 5), moving_average(\"rsi_antenna3\", 5), moving_average(\"rsi_antenna4\", 5), moving_average(\"rssi\", 20) FROM \"router.wifi.clients\" WHERE (\"hostname\" =~ /^$routerHostsWifi$/) AND $timeFilter GROUP BY \"hostname\", \"client\", \"ip\"",
       "select": [
        [
         { "params": [ "rssi" ], "type": "field" },
         { "params": [ "10" ], "type": "moving_average" },
         { "params": [ "rsi" ], "type": "alias" }
        ],
        [
         { "params": [ "rsi_antenna1" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "antenna1" ], "type": "alias" }
        ],
        [
         { "params": [ "rsi_antenna2" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "antenna2" ], "type": "alias" }
        ],
        [
         { "params": [ "rsi_antenna3" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "antenna3" ], "type": "alias" }
        ],
        [
         { "params": [ "rsi_antenna4" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "antenna4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "title": "Noise",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 7, "y": 120 },
     "yaxes": [
      { "format": "dBm" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
       "select": [
        [
         { "params": [ "noise_antenna_1" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "Noise Antenna 1" ], "type": "alias" }
        ],
        [
         { "params": [ "noise_antenna_2" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "Noise Antenna 2" ], "type": "alias" }
        ],
        [
         { "params": [ "noise_antenna_3" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "Noise Antenna 3" ], "type": "alias" }
        ],
        [
         { "params": [ "noise_antenna_4" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "Noise Antenna 4" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "title": "Rx/Tx ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 13, "y": 120 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" },
        { "params": [ "client" ], "type": "tag" },
        { "params": [ "ip" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
       "select": [
        [
         { "params": [ "rx_rate_pkt" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "rx_rate_pkt" ], "type": "alias" }
        ],
        [
         { "params": [ "tx1_rate_pkt" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "tx1_rate_pkt" ], "type": "alias" }
        ],
        [
         { "params": [ "tx2_rate_pkt" ], "type": "field" },
         { "params": [ "5" ], "type": "moving_average" },
         { "params": [ "tx2_rate_pkt" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ]
      }
     ]
    },
    {
     "title": "2.4 / 5Ghz Channel",
     "type": "graph",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 120 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "alias": "WifiBand",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "groupBy": [
        { "params": [ "hostname" ], "type": "tag" }
       ],
       "measurement": "router.wifi.clients",
       "query": "SELECT \"rsi_antenna_avg_1\", \"rsi_antenna_avg_2\", \"rsi_antenna_avg_3\", \"rsi_antenna_avg_4\" FROM \"router.wifi.clients\" WHERE (\"hostname\" = 'StefansiPhone2') AND $timeFilter GROUP BY \"hostname\", \"client\"",
       "select": [
        [
         { "params": [ "wifiBand" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "hostname", "operator": "=~", "value": "/^$routerHostsWifi$/" }
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "Network traffic on $Interfaces ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 199 },
   "repeat": "Interfaces",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "router.network",
     "select": [
      [
       { "params": [ "recv_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "trans_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$routerHost$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$Interfaces$/" }
     ]
    }
   ]
  },
  { "title": "Workstations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 } },
  {
   "title": "$trafficHosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 256 },
   "repeat": "trafficHosts",
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "inBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" }
     ],
     "measurement": "router.client_traffic",
     "select": [
      [
       { "params": [ "outBytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$trafficHosts$/" }
     ]
    }
   ]
  }
 ]
}