{
 "title": "F5 Physical Load Balancers",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "FIT-F5-A: CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_bigip_cpu_percent{state=\"System\", hostname=\"fit-f5-a.hpl.com\"} + on() f5_bigip_cpu_percent{state=\"User\", hostname=\"fit-f5-a.hpl.com\"}"
    }
   ]
  },
  {
   "title": "FIT-F5-B: CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_bigip_cpu_percent{state=\"System\", hostname=\"fit-f5-b.hpl.com\"} + on() f5_bigip_cpu_percent{state=\"User\", hostname=\"fit-f5-b.hpl.com\"}"
    }
   ]
  },
  {
   "title": "FIT-F5-A: CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_cpu_percent{state=\"System\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "% System CPU"
    },
    {
     "expr": "f5_bigip_cpu_percent{state=\"User\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "% User CPU"
    }
   ]
  },
  {
   "title": "FIT-F5-A: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_memory_bytes{type=\"Used\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "Used memory"
    },
    {
     "expr": "f5_bigip_memory_bytes{type=\"Total\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "FIT-F5-B: CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_cpu_percent{state=\"System\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "% System CPU"
    },
    {
     "expr": "f5_bigip_cpu_percent{state=\"User\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "% User CPU"
    }
   ]
  },
  {
   "title": "FIT-F5-B: Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_memory_bytes{type=\"Used\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "Used memory"
    },
    {
     "expr": "f5_bigip_memory_bytes{type=\"Total\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "FIT-F5-A: Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_active_conn{profile=\"Client\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "Client Conn"
    },
    {
     "expr": "f5_bigip_active_conn{profile=\"Server\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "Server Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-A: Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_active_conn{profile=\"Client\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "Client Conn"
    },
    {
     "expr": "f5_bigip_active_conn{profile=\"Server\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "Server Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-A: Total Connections/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_conn_total{profile=\"Client\", hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Client Conn"
    },
    {
     "expr": "rate(f5_bigip_conn_total{profile=\"Server\", hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Server Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-B: Total Connections/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_conn_total{profile=\"Client\", hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Client Conn"
    },
    {
     "expr": "rate(f5_bigip_conn_total{profile=\"Server\", hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Server Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-A: Active VS Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_vs_conn{name=\"typhonmp.hpl.com_443_vs\",hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "typhonmp.hpl.com_vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"aspnet.pharmacyonesource.com_private_443_vs\",hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "aspnet.p1s.com_priv__vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"aspnet.pharmacyonesource.com_443_vs\",hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "aspnet.p1s.com_vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"rls.hpl.com_443_vs\",hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "rls.hpl.com_vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"apps.pharmacyonesource.com_private_443_vs\",hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "apps.p1s.com_vs Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-B: Active VS Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_vs_conn{name=\"typhonmp.hpl.com_443_vs\",hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "typhonmp.hpl.com_vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"aspnet.pharmacyonesource.com_private_443_vs\",hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "aspnet.p1s.com_priv__vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"aspnet.pharmacyonesource.com_443_vs\",hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "aspnet.p1s.com_vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"rls.hpl.com_443_vs\",hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "rls.hpl.com_vs Conn"
    },
    {
     "expr": "f5_bigip_vs_conn{name=\"apps.pharmacyonesource.com_private_443_vs\",hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "apps.p1s.com_vs Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-A: Active SSL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_active_ssl_conn{profile=\"Client\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "Client SSL Conn"
    },
    {
     "expr": "f5_bigip_active_ssl_conn{profile=\"Server\", hostname=\"fit-f5-a.hpl.com\"}",
     "legendFormat": "Server SSL Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-B: Active SSL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_bigip_active_ssl_conn{profile=\"Client\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "Client SSL Conn"
    },
    {
     "expr": "f5_bigip_active_ssl_conn{profile=\"Server\", hostname=\"fit-f5-b.hpl.com\"}",
     "legendFormat": "Server SSL Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-A: SSL Connections/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_ssl_conn_total{profile=\"Client\", hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Client SSL Conn"
    },
    {
     "expr": "rate(f5_bigip_ssl_conn_total{profile=\"Server\", hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Server SSL Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-B: SSL Connections/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_ssl_conn_total{profile=\"Client\", hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Client SSL Conn"
    },
    {
     "expr": "rate(f5_bigip_ssl_conn_total{profile=\"Server\", hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval])",
     "legendFormat": "Server SSL Conn"
    }
   ]
  },
  {
   "title": "FIT-F5-A: HTTP Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_http_requests_total{type=\"System\", hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval])",
     "legendFormat": "HTTP Requests"
    }
   ]
  },
  {
   "title": "FIT-F5-B: HTTP Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_http_requests_total{type=\"System\", hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval])",
     "legendFormat": "HTTP Requests"
    }
   ]
  },
  {
   "title": "FIT-F5-A: Throughput Mbits/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Client_Out\",hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval]) * 8",
     "legendFormat": "Client outbound"
    },
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Client_In\",hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval]) * -8",
     "legendFormat": "Client inbound"
    },
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Server_Out\",hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval]) * 8",
     "legendFormat": "Server outbound"
    },
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Server_In\",hostname=\"fit-f5-a.hpl.com\"}[$__rate_interval]) * -8",
     "legendFormat": "Server inbound"
    }
   ]
  },
  {
   "title": "FIT-F5-B: Throughput Mbits/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Client_Out\",hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval]) * 8",
     "legendFormat": "Client outbound"
    },
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Client_In\",hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval]) * -8",
     "legendFormat": "Client inbound"
    },
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Server_Out\",hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval]) * 8",
     "legendFormat": "Server outbound"
    },
    {
     "expr": "rate(f5_bigip_network_traffic_bytes{profile=\"Server_In\",hostname=\"fit-f5-b.hpl.com\"}[$__rate_interval]) * -8",
     "legendFormat": "Server inbound"
    }
   ]
  }
 ]
}