{
 "title": "Kemp Loadmaster",
 "description": "Dashboard for quickly showing important metrics of Kemp's load balancer solution.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "device", "query": { "query": "vSstate" } }
  ]
 },
 "panels": [
  {
   "title": "Virtual Services Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(vSState_info{vSState=\"inService\"} == 1) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Virtual Services Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(vSState_info{vSState=\"sorry\"} == 1) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ssCpuIdle{device=\"$device\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "memTotalFree{device=\"$device\"}\t"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifInOctets{device=\"$device\"}[2m]) * 8 > 0",
     "legendFormat": "Inbound"
    },
    {
     "expr": "0 - irate(ifOutOctets{device=\"$device\"}[2m]) * 8 > 0",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Throughput per virtual service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(vSOutBytes{device=\"$device\"}[5m]) * 8 > 0",
     "legendFormat": "{{vSIdx}}"
    }
   ]
  },
  {
   "title": "Active connections per virtual service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vSActiveConns{device=\"$device\"} > 0",
     "legendFormat": "{{vSIdx}}"
    }
   ]
  },
  {
   "title": "Used bandwidth past 24 hours - Top 5 ",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5,increase(vSOutBytes{device=\"$device\"}[1d]))"
    }
   ]
  }
 ]
}