{
 "title": "PA firewalls",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "PAN HA Cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "pan_firewall", "label": "PAN Firewall", "query": { "query": "label_values(agent_host)" } }
  ]
 },
 "panels": [
  { "title": "Base metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PAN Firewall state",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pan_firewall_uptime{agent_host=\"$pan_firewall\",cluster=\"$cluster\",panSysHAState=\"active\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "PAN Firewall version",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max(pan_firewall_uptime{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}) by (pa_version)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "PAN Firewall Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pan_firewall_uptime{agent_host=\"$pan_firewall\",cluster=\"$cluster\"} / 60",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "PAN CPU Load (Control plane)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pan_firewall_hrProcessorLoad_1{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "PAN CPU Load (Data plane)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pan_firewall_hrProcessorLoad_2{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "PAN CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pan_firewall_hrProcessorLoad_1{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "% CPU Load 1"
    },
    {
     "expr": "pan_firewall_hrProcessorLoad_2{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "% CPU Load 2"
    }
   ]
  },
  {
   "title": "PAN Mgmt Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pan_buffers_hrStorageUsed{agent_host=\"$pan_firewall\",cluster=\"$cluster\",hrStorageDescr=\"Slot-1 Management Memory\"} * 1024",
     "legendFormat": "Used memory"
    },
    {
     "expr": "pan_buffers_hrStorageSize{agent_host=\"$pan_firewall\",cluster=\"$cluster\",hrStorageDescr=\"Slot-1 Management Memory\"} * 1024",
     "legendFormat": "Total memory"
    }
   ]
  },
  {
   "title": "PAN tunnel.1: Throughput Mbits/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "rate(pan_interfaces_ifHCInOctets{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.1\"}[$__rate_interval]) * 8",
     "legendFormat": "In Octets"
    },
    {
     "expr": "rate(pan_interfaces_ifHCOutOctets{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.1\"}[$__rate_interval]) * -8",
     "legendFormat": "Out Octets"
    }
   ]
  },
  {
   "title": "PAN tunnel.1 Errors & Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pan_interfaces_ifInDiscards{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.1\"}[$__rate_interval])",
     "legendFormat": "In Discards"
    },
    {
     "expr": "increase(pan_interfaces_ifOutDiscards{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.1\"}[$__rate_interval]) * -1",
     "legendFormat": "Out Discards"
    },
    {
     "expr": "increase(pan_interfaces_ifInErrors{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.1\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "increase(pan_interfaces_ifOutErrors{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.1\"}[$__rate_interval]) * -1",
     "legendFormat": "Out Errors"
    }
   ]
  },
  {
   "title": "PAN tunnel.2: Throughput Mbits/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "rate(pan_interfaces_ifHCInOctets{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.2\"}[$__rate_interval]) * 8",
     "legendFormat": "In Octets"
    },
    {
     "expr": "rate(pan_interfaces_ifHCOutOctets{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.2\"}[$__rate_interval]) * -8",
     "legendFormat": "Out Octets"
    }
   ]
  },
  {
   "title": "PAN tunnel.2 Errors & Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pan_interfaces_ifInDiscards{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.2\"}[$__rate_interval])",
     "legendFormat": "In Discards"
    },
    {
     "expr": "increase(pan_interfaces_ifOutDiscards{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.2\"}[$__rate_interval]) * -1",
     "legendFormat": "Out Discards"
    },
    {
     "expr": "increase(pan_interfaces_ifInErrors{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.2\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "increase(pan_interfaces_ifOutErrors{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.2\"}[$__rate_interval]) * -1",
     "legendFormat": "Out Errors"
    }
   ]
  },
  {
   "title": "PAN tunnel.3: Throughput Mbits/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "rate(pan_interfaces_ifHCInOctets{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.3\"}[$__rate_interval]) * 8",
     "legendFormat": "In Octets"
    },
    {
     "expr": "rate(pan_interfaces_ifHCOutOctets{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.3\"}[$__rate_interval]) * -8",
     "legendFormat": "Out Octets"
    }
   ]
  },
  {
   "title": "PAN tunnel.3 Errors & Discards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pan_interfaces_ifInDiscards{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.3\"}[$__rate_interval])",
     "legendFormat": "In Discards"
    },
    {
     "expr": "increase(pan_interfaces_ifOutDiscards{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.3\"}[$__rate_interval]) * -1",
     "legendFormat": "Out Discards"
    },
    {
     "expr": "increase(pan_interfaces_ifInErrors{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.3\"}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "increase(pan_interfaces_ifOutErrors{agent_host=\"$pan_firewall\",cluster=\"$cluster\",if_name=\"tunnel.3\"}[$__rate_interval]) * -1",
     "legendFormat": "Out Errors"
    }
   ]
  },
  {
   "title": "PAN Session Discards & Denies",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pan_drop_panSessionDiscard{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Discarded Sessions"
    },
    {
     "expr": "increase(pan_drop_panFlowHostServiceDeny{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Service Denies"
    }
   ]
  },
  {
   "title": "PAN TCP Drops",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(pan_global_counters_panTcpDropPacket{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "TCP drops"
    },
    {
     "expr": "increase(pan_global_counters_panTcpDropOutOfWnd{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "TCP OOW drops"
    },
    {
     "expr": "increase(pan_global_counters_panTcpExceedSegLimit{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "TCP Exceed MSS"
    }
   ]
  },
  {
   "title": "PAN Vsys Active Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pan_vsys_panVsysActiveSessions{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "Active Sessions"
    }
   ]
  },
  {
   "title": "PAN Vsys TCP & UDP Conn/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pan_vsys_panVsysActiveTcpCps{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "TCP Conn/sec"
    },
    {
     "expr": "pan_vsys_panVsysActiveUdpCps{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "UDP Conn/sec"
    }
   ]
  },
  { "title": "Hardware metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "PAN Fan speeds (RPM)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pan_firewall_fan1{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "Fan1"
    },
    {
     "expr": "pan_firewall_fan2{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "Fan2"
    },
    {
     "expr": "pan_firewall_fan3{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "Fan3"
    }
   ]
  },
  {
   "title": "PAN CPU temp (Celcius)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pan_firewall_cpu_temp1{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "CPU Temp #1"
    },
    {
     "expr": "pan_firewall_cpu_temp2{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "CPU Temp #2"
    },
    {
     "expr": "pan_firewall_cpu_temp3{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "CPU Temp #3"
    },
    {
     "expr": "pan_firewall_cpu_temp4{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "CPU Temp #4"
    },
    {
     "expr": "pan_firewall_cpu_temp5{agent_host=\"$pan_firewall\",cluster=\"$cluster\"}",
     "legendFormat": "CPU Temp #5"
    }
   ]
  }
 ]
}