{
 "title": "TeamCity",
 "description": "TeamCity 2019.2 metrics dashboard",
 "tags": [ "teamcity" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Server Uptime",
   "type": "stat",
   "description": "Time since the server process started initializing",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_uptime_milliseconds" }
   ]
  },
  {
   "title": "Active Project Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "projects_active_number" }
   ]
  },
  {
   "title": "Build Configurations Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "buildConfigurations_number" }
   ]
  },
  {
   "title": "vcsRoot Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vcsRoots_number" }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_count_number" }
   ]
  },
  {
   "title": "Authorized Agents Count",
   "type": "stat",
   "description": "Number of connected and authorized build agents",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agents_connected_authorized_number"
    }
   ]
  },
  {
   "title": "Build Count Information",
   "type": "graph",
   "description": "Number of builds which are either running or queued",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "builds_running_number", "legendFormat": "builds_running" },
    { "expr": "builds_queued_number", "legendFormat": "builds_queued" }
   ]
  },
  {
   "title": "Users Active",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "users_active_number", "legendFormat": "users_active" }
   ]
  },
  {
   "title": "Active HTTP Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "httpSessions_active_number", "legendFormat": "http_sessions_active" }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id='PS Eden Space'}",
     "legendFormat": "PS Eden Space"
    },
    {
     "expr": "jvm_memory_used_bytes{id='PS Old Gen'}",
     "legendFormat": "PS Old Gen"
    },
    {
     "expr": "jvm_memory_used_bytes{id='PS Survivor Space'}",
     "legendFormat": "PS Survivor Space"
    },
    {
     "expr": "jvm_memory_used_bytes{id='Code Cache'}",
     "legendFormat": "Code Cache"
    },
    {
     "expr": "jvm_memory_used_bytes{id='Compressed Class Space'}",
     "legendFormat": "Compressed Class Space"
    },
    {
     "expr": "jvm_memory_used_bytes{id='Metaspace'}",
     "legendFormat": "Metaspace"
    }
   ]
  },
  {
   "title": "JVM Threads Count",
   "type": "graph",
   "description": "The current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_number", "legendFormat": "jvm_threads" }
   ]
  }
 ]
}