{
 "title": "TrueNAS",
 "tags": [
  "TrueNAS",
  "FreeNAS"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(servers_nas_lucasnet_int_uptime_uptime, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_uptime_uptime ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Disk Temperature (°C)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_disktemp_ada0_temperature",
     "legendFormat": "ada0 - hdd_pool"
    },
    {
     "expr": "servers_nas_lucasnet_int_disktemp_ada1_temperature",
     "legendFormat": "ada1 - hdd_pool"
    },
    {
     "expr": "servers_nas_lucasnet_int_disktemp_nvd0_temperature",
     "legendFormat": "nvd0 - nvme_pool"
    },
    {
     "expr": "servers_nas_lucasnet_int_disktemp_nvd1_temperature",
     "legendFormat": "nvd1 - slog"
    },
    {
     "expr": "servers_nas_lucasnet_int_disktemp_da0_temperature",
     "legendFormat": "da0 - boot"
    }
   ]
  },
  {
   "title": "nvme_pool Space Free",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_df_mnt_nvme_pool_df_complex_free",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "hdd_pool Space Free",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_df_mnt_hdd_pool_df_complex_free",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "boot Space Free",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_df_root_df_complex_free",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU idle",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_cpu_0_percent_idle",
     "legendFormat": "CPU #0"
    },
    {
     "expr": "servers_nas_lucasnet_int_cpu_1_percent_idle",
     "legendFormat": "CPU #1"
    },
    {
     "expr": "servers_nas_lucasnet_int_cpu_2_percent_idle",
     "legendFormat": "CPU #2"
    },
    {
     "expr": "servers_nas_lucasnet_int_cpu_3_percent_idle",
     "legendFormat": "CPU #3"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_load_load_longterm",
     "legendFormat": "logterm"
    },
    { "expr": "truenas_load_midterm", "legendFormat": "midterm" },
    { "expr": "truenas_load_shortterm", "legendFormat": "shortterm" }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_swap_swap_used",
     "legendFormat": "used"
    },
    {
     "expr": "servers_nas_lucasnet_int_swap_swap_free",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "(servers_nas_lucasnet_int_cputemp_0_temperature / 10) - 273.15",
     "legendFormat": "CPU #0"
    },
    {
     "expr": "(servers_nas_lucasnet_int_cputemp_1_temperature / 10) - 273.15",
     "legendFormat": "CPU #1"
    },
    {
     "expr": "(servers_nas_lucasnet_int_cputemp_2_temperature / 10) - 273.15",
     "legendFormat": "CPU #2"
    },
    {
     "expr": "(servers_nas_lucasnet_int_cputemp_3_temperature / 10) - 273.15",
     "legendFormat": "CPU #3"
    }
   ]
  },
  {
   "title": "Physical Memory Utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_memory_memory_free",
     "legendFormat": "Free"
    },
    {
     "expr": "servers_nas_lucasnet_int_memory_memory_active",
     "legendFormat": "Active"
    },
    {
     "expr": "servers_nas_lucasnet_int_memory_memory_inactive",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Disk I/O time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_disk_ada0_disk_io_time_weighted_io_time",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "servers_nas_lucasnet_int_disk_ada1_disk_io_time_weighted_io_time",
     "legendFormat": "__auto"
    },
    {
     "expr": "servers_nas_lucasnet_int_disk_nvd0_disk_io_time_weighted_io_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ARC Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_zfs_arc_cache_size_arc",
     "legendFormat": "ARC"
    },
    {
     "expr": "servers_nas_lucasnet_int_zfs_arc_cache_size_L2",
     "legendFormat": "L2"
    }
   ]
  },
  {
   "title": "ARC Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_zfs_arc_cache_ratio_arc  * 100",
     "legendFormat": "ARC"
    }
   ]
  },
  {
   "title": "br0 Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_interface_bridge0_if_octets_rx / 800",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "servers_nas_lucasnet_int_interface_bridge0_if_octets_tx / 800",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "br100 Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_interface_bridge100_if_octets_rx / 800",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "servers_nas_lucasnet_int_interface_bridge100_if_octets_tx / 800",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "br101 Interface Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_interface_bridge101_if_octets_rx / 800",
     "legendFormat": "{{device}} in"
    },
    {
     "expr": "servers_nas_lucasnet_int_interface_bridge101_if_octets_tx / 800",
     "legendFormat": "{{device}} out"
    }
   ]
  },
  {
   "title": "NFS OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "servers_nas_lucasnet_int_nfsstat_server_nfsstat_read",
     "legendFormat": "v3 read"
    },
    {
     "expr": "servers_nas_lucasnet_int_nfsstat_server_nfsstat_write",
     "legendFormat": "v3 write"
    }
   ]
  }
 ]
}